const TEST_INCREMENT = 'TEST_INCREMENT';
const TEST_DECREMENT = 'TEST_DECREMENT';

// user reducer
const USER_LOGIN = 'USER_LOGIN';
const USER_INFO = 'USER_INFO';
const USER_LOGOUT = 'USER_LOGOUT';
const USER_PAYMENT = 'USER_PAYMENT';

// assets reducer
const ASSETS_UPDATE = 'ASSETS_UPDATE';
const ASSETS_SHOW_STATE_CHENGE = 'ASSETS_SHOW_STATE_CHENGE';
const ASSETS_UPDATE_BILL_TYPE = 'ASSETS_UPDATE_BILL_TYPE';
const ASSETS_UPDATE_BILL_TIME_TYPE = 'ASSETS_UPDATE_BILL_TIME_TYPE';

//otc state reducer
const OTC_STATE_CHANGE_DANGER = 'OTC_STATE_CHANGE_DANGER';

//ad list reducer
const UPDATE_AD_LIST_DATA = 'UPDATE_AD_LIST_DATA';

//order list reducer
const UPDATE_ORDER_LIST_DATA = 'UPDATE_ORDER_LIST_DATA';

//country code
const COUNTRY_CODE_CHANGE = 'COUNTRY_CODE_CHANGE';
const BOUNDRY_CODE_CHANGE = 'BOUNDRY_CODE_CHANGE';

export {
    TEST_INCREMENT,
    TEST_DECREMENT,

    USER_LOGIN,
    USER_INFO,
    USER_LOGOUT,
    USER_PAYMENT,

    ASSETS_UPDATE,
    ASSETS_SHOW_STATE_CHENGE,
    ASSETS_UPDATE_BILL_TYPE,
    ASSETS_UPDATE_BILL_TIME_TYPE,

    OTC_STATE_CHANGE_DANGER,

    UPDATE_AD_LIST_DATA,

    UPDATE_ORDER_LIST_DATA,

    COUNTRY_CODE_CHANGE,
    BOUNDRY_CODE_CHANGE
}